/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4-152-gdf288deb9b-20210919"
#endif /* AVUTIL_FFVERSION_H */
